# Generated by Django 5.1.3 on 2024-12-05 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_contest_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contestparticipation',
            index=models.Index(fields=['user', 'contest'], name='contests_co_user_id_affbb0_idx'),
        ),
    ]
