# Generated by Django 5.1.3 on 2024-12-07 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contestparticipation_contests_co_user_id_affbb0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator]),
        ),
    ]
