# Generated by Django 5.1.3 on 2024-12-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_contestparticipation_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestparticipation',
            old_name='points',
            new_name='pionts',
        ),
    ]
