# Generated by Django 5.1.3 on 2024-12-05 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'problem')},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='contest',
        ),
    ]
