# Generated by Django 5.1.3 on 2024-12-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_submissions_user_id_1304bb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.TextField(default='python', max_length=10),
        ),
    ]
