# Generated by Django 5.1.3 on 2024-12-10 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submission_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
