# Generated by Django 5.1.3 on 2024-12-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contestparticipation_contests_co_user_id_affbb0_idx'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='point',
            new_name='points',
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['contest', 'title'], name='problems_pr_contest_9f6b06_idx'),
        ),
    ]
