# Generated by Django 5.1.3 on 2024-12-07 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_rename_point_problem_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('mid', 'Mid'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
