# Generated by Django 5.1.3 on 2024-12-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_is_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='is_submitted',
        ),
    ]
