# Generated by Django 5.1.3 on 2024-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_remove_problem_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_description',
            field=models.TextField(default=''),
        ),
    ]
