# Generated by Django 5.1.3 on 2024-12-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0006_remove_problem_is_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('C', 'C'), ('CPP', 'C++'), ('CSHARP', 'C#'), ('JAVA', 'Java'), ('JS', 'JavaScript'), ('PY', 'Python'), ('GO', 'Go')], max_length=10)),
                ('code_snippet', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_codes', to='problems.problem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('language', 'problem'), name='unique_language_problem')],
            },
        ),
    ]
