# Generated by Django 5.1.3 on 2024-12-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingspace', '0002_alter_defaultcode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcode',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('cs', 'C#'), ('java', 'Java'), ('js', 'JavaScript'), ('py', 'Python'), ('go', 'Go')], max_length=10),
        ),
    ]
